development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:b79c8f743004b21acfab815526903d30@jack.redistogo.com:11025/
  host: jack.redistogo.com
  port: 11025
  password: b79c8f743004b21acfab815526903d30
