# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a45831a1b1fb943a81dea35fac62ab93e40e3f98fb33b0150ba085a8121a9d7bb1f52305f383c277aa4b2fee6e33746a16ce0e84c19bb30c7b56ca4ce4102d7

test:
  secret_key_base: 2078c379812e189fa5aa45a30c086ded63015f1a09741be3f80e10712ac7e3238eceea55c3abee637c3890203e7cd9abe83a34ba7528d12337331fe7dc08819c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
